# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: mia1024
          template: classic
          debug: no
          base: header, repositories, metadata, activity, community,
          base_indepth: yes
          config_timezone: America/Los_Angeles
          plugins_errors_fatal: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_analysis_timeout_repositories: 30
          plugin_languages_sections: recently-used, most-used
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 180
          plugin_languages_recent_load: 300
          plugin_languages_threshold: 0%
          plugin_languages_details: lines
          
          plugin_lines: yes
          plugin_lines_history_limit: 10
          plugin_lines_repositories_limit: 100
          plugin_lines_sections: base
          repositories_affiliations: owner, collaborator
